#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace e_ticaret
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="e-ticaret")]
	public partial class kaynakDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertKategori(Kategori instance);
    partial void UpdateKategori(Kategori instance);
    partial void DeleteKategori(Kategori instance);
    partial void InserttblKullanici(tblKullanici instance);
    partial void UpdatetblKullanici(tblKullanici instance);
    partial void DeletetblKullanici(tblKullanici instance);
    partial void InserttblMarka(tblMarka instance);
    partial void UpdatetblMarka(tblMarka instance);
    partial void DeletetblMarka(tblMarka instance);
    partial void InserttblSepet(tblSepet instance);
    partial void UpdatetblSepet(tblSepet instance);
    partial void DeletetblSepet(tblSepet instance);
    partial void InserttblSipari(tblSipari instance);
    partial void UpdatetblSipari(tblSipari instance);
    partial void DeletetblSipari(tblSipari instance);
    partial void InserttblSiparisDetay(tblSiparisDetay instance);
    partial void UpdatetblSiparisDetay(tblSiparisDetay instance);
    partial void DeletetblSiparisDetay(tblSiparisDetay instance);
    partial void InsertUrun(Urun instance);
    partial void UpdateUrun(Urun instance);
    partial void DeleteUrun(Urun instance);
    #endregion
		
		public kaynakDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["e_ticaretConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public kaynakDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kaynakDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kaynakDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public kaynakDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Kategori> Kategoris
		{
			get
			{
				return this.GetTable<Kategori>();
			}
		}
		
		public System.Data.Linq.Table<tblKullanici> tblKullanicis
		{
			get
			{
				return this.GetTable<tblKullanici>();
			}
		}
		
		public System.Data.Linq.Table<tblMarka> tblMarkas
		{
			get
			{
				return this.GetTable<tblMarka>();
			}
		}
		
		public System.Data.Linq.Table<tblSepet> tblSepets
		{
			get
			{
				return this.GetTable<tblSepet>();
			}
		}
		
		public System.Data.Linq.Table<tblSipari> tblSiparis
		{
			get
			{
				return this.GetTable<tblSipari>();
			}
		}
		
		public System.Data.Linq.Table<tblSiparisDetay> tblSiparisDetays
		{
			get
			{
				return this.GetTable<tblSiparisDetay>();
			}
		}
		
		public System.Data.Linq.Table<Urun> Uruns
		{
			get
			{
				return this.GetTable<Urun>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Kategori")]
	public partial class Kategori : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Id;
		
		private string _KatAdi;
		
		private EntitySet<Urun> _Uruns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnKatAdiChanging(string value);
    partial void OnKatAdiChanged();
    #endregion
		
		public Kategori()
		{
			this._Uruns = new EntitySet<Urun>(new Action<Urun>(this.attach_Uruns), new Action<Urun>(this.detach_Uruns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KatAdi", DbType="VarChar(550)")]
		public string KatAdi
		{
			get
			{
				return this._KatAdi;
			}
			set
			{
				if ((this._KatAdi != value))
				{
					this.OnKatAdiChanging(value);
					this.SendPropertyChanging();
					this._KatAdi = value;
					this.SendPropertyChanged("KatAdi");
					this.OnKatAdiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Urun", Storage="_Uruns", ThisKey="Id", OtherKey="KatId")]
		public EntitySet<Urun> Uruns
		{
			get
			{
				return this._Uruns;
			}
			set
			{
				this._Uruns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = this;
		}
		
		private void detach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.Kategori = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblKullanici")]
	public partial class tblKullanici : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kullaniciKod;
		
		private string _email;
		
		private string _adsoyad;
		
		private System.Nullable<System.DateTime> _sonGirisTarih;
		
		private string _sifre;
		
		private string _sehir;
		
		private string _adres1;
		
		private string _tel;
		
		private System.Nullable<int> _puan;
		
		private string _Dtarih;
		
		private System.Nullable<bool> _Cinsiyet;
		
		private System.Nullable<bool> _Yonetim;
		
		private EntitySet<tblSepet> _tblSepets;
		
		private EntitySet<tblSipari> _tblSiparis;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkullaniciKodChanging(int value);
    partial void OnkullaniciKodChanged();
    partial void OnemailChanging(string value);
    partial void OnemailChanged();
    partial void OnadsoyadChanging(string value);
    partial void OnadsoyadChanged();
    partial void OnsonGirisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnsonGirisTarihChanged();
    partial void OnsifreChanging(string value);
    partial void OnsifreChanged();
    partial void OnsehirChanging(string value);
    partial void OnsehirChanged();
    partial void Onadres1Changing(string value);
    partial void Onadres1Changed();
    partial void OntelChanging(string value);
    partial void OntelChanged();
    partial void OnpuanChanging(System.Nullable<int> value);
    partial void OnpuanChanged();
    partial void OnDtarihChanging(string value);
    partial void OnDtarihChanged();
    partial void OnCinsiyetChanging(System.Nullable<bool> value);
    partial void OnCinsiyetChanged();
    partial void OnYonetimChanging(System.Nullable<bool> value);
    partial void OnYonetimChanged();
    #endregion
		
		public tblKullanici()
		{
			this._tblSepets = new EntitySet<tblSepet>(new Action<tblSepet>(this.attach_tblSepets), new Action<tblSepet>(this.detach_tblSepets));
			this._tblSiparis = new EntitySet<tblSipari>(new Action<tblSipari>(this.attach_tblSiparis), new Action<tblSipari>(this.detach_tblSiparis));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciKod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int kullaniciKod
		{
			get
			{
				return this._kullaniciKod;
			}
			set
			{
				if ((this._kullaniciKod != value))
				{
					this.OnkullaniciKodChanging(value);
					this.SendPropertyChanging();
					this._kullaniciKod = value;
					this.SendPropertyChanged("kullaniciKod");
					this.OnkullaniciKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email", DbType="NVarChar(50)")]
		public string email
		{
			get
			{
				return this._email;
			}
			set
			{
				if ((this._email != value))
				{
					this.OnemailChanging(value);
					this.SendPropertyChanging();
					this._email = value;
					this.SendPropertyChanged("email");
					this.OnemailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adsoyad", DbType="NVarChar(30)")]
		public string adsoyad
		{
			get
			{
				return this._adsoyad;
			}
			set
			{
				if ((this._adsoyad != value))
				{
					this.OnadsoyadChanging(value);
					this.SendPropertyChanging();
					this._adsoyad = value;
					this.SendPropertyChanged("adsoyad");
					this.OnadsoyadChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sonGirisTarih", DbType="SmallDateTime")]
		public System.Nullable<System.DateTime> sonGirisTarih
		{
			get
			{
				return this._sonGirisTarih;
			}
			set
			{
				if ((this._sonGirisTarih != value))
				{
					this.OnsonGirisTarihChanging(value);
					this.SendPropertyChanging();
					this._sonGirisTarih = value;
					this.SendPropertyChanged("sonGirisTarih");
					this.OnsonGirisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sifre", DbType="NVarChar(12)")]
		public string sifre
		{
			get
			{
				return this._sifre;
			}
			set
			{
				if ((this._sifre != value))
				{
					this.OnsifreChanging(value);
					this.SendPropertyChanging();
					this._sifre = value;
					this.SendPropertyChanged("sifre");
					this.OnsifreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sehir", DbType="NVarChar(50)")]
		public string sehir
		{
			get
			{
				return this._sehir;
			}
			set
			{
				if ((this._sehir != value))
				{
					this.OnsehirChanging(value);
					this.SendPropertyChanging();
					this._sehir = value;
					this.SendPropertyChanged("sehir");
					this.OnsehirChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adres1", DbType="NVarChar(50)")]
		public string adres1
		{
			get
			{
				return this._adres1;
			}
			set
			{
				if ((this._adres1 != value))
				{
					this.Onadres1Changing(value);
					this.SendPropertyChanging();
					this._adres1 = value;
					this.SendPropertyChanged("adres1");
					this.Onadres1Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_tel", DbType="Char(13)")]
		public string tel
		{
			get
			{
				return this._tel;
			}
			set
			{
				if ((this._tel != value))
				{
					this.OntelChanging(value);
					this.SendPropertyChanging();
					this._tel = value;
					this.SendPropertyChanged("tel");
					this.OntelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_puan", DbType="Int")]
		public System.Nullable<int> puan
		{
			get
			{
				return this._puan;
			}
			set
			{
				if ((this._puan != value))
				{
					this.OnpuanChanging(value);
					this.SendPropertyChanging();
					this._puan = value;
					this.SendPropertyChanged("puan");
					this.OnpuanChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dtarih", DbType="VarChar(50)")]
		public string Dtarih
		{
			get
			{
				return this._Dtarih;
			}
			set
			{
				if ((this._Dtarih != value))
				{
					this.OnDtarihChanging(value);
					this.SendPropertyChanging();
					this._Dtarih = value;
					this.SendPropertyChanged("Dtarih");
					this.OnDtarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Cinsiyet", DbType="Bit")]
		public System.Nullable<bool> Cinsiyet
		{
			get
			{
				return this._Cinsiyet;
			}
			set
			{
				if ((this._Cinsiyet != value))
				{
					this.OnCinsiyetChanging(value);
					this.SendPropertyChanging();
					this._Cinsiyet = value;
					this.SendPropertyChanged("Cinsiyet");
					this.OnCinsiyetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Yonetim", DbType="Bit")]
		public System.Nullable<bool> Yonetim
		{
			get
			{
				return this._Yonetim;
			}
			set
			{
				if ((this._Yonetim != value))
				{
					this.OnYonetimChanging(value);
					this.SendPropertyChanging();
					this._Yonetim = value;
					this.SendPropertyChanged("Yonetim");
					this.OnYonetimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKullanici_tblSepet", Storage="_tblSepets", ThisKey="kullaniciKod", OtherKey="kullaniciKod")]
		public EntitySet<tblSepet> tblSepets
		{
			get
			{
				return this._tblSepets;
			}
			set
			{
				this._tblSepets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKullanici_tblSipari", Storage="_tblSiparis", ThisKey="kullaniciKod", OtherKey="kullaniciKod")]
		public EntitySet<tblSipari> tblSiparis
		{
			get
			{
				return this._tblSiparis;
			}
			set
			{
				this._tblSiparis.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSepets(tblSepet entity)
		{
			this.SendPropertyChanging();
			entity.tblKullanici = this;
		}
		
		private void detach_tblSepets(tblSepet entity)
		{
			this.SendPropertyChanging();
			entity.tblKullanici = null;
		}
		
		private void attach_tblSiparis(tblSipari entity)
		{
			this.SendPropertyChanging();
			entity.tblKullanici = this;
		}
		
		private void detach_tblSiparis(tblSipari entity)
		{
			this.SendPropertyChanging();
			entity.tblKullanici = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblMarka")]
	public partial class tblMarka : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _markaKod;
		
		private string _Marka;
		
		private string _MarkaTel;
		
		private string _MarkaResim;
		
		private EntitySet<Urun> _Uruns;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnmarkaKodChanging(int value);
    partial void OnmarkaKodChanged();
    partial void OnMarkaChanging(string value);
    partial void OnMarkaChanged();
    partial void OnMarkaTelChanging(string value);
    partial void OnMarkaTelChanged();
    partial void OnMarkaResimChanging(string value);
    partial void OnMarkaResimChanged();
    #endregion
		
		public tblMarka()
		{
			this._Uruns = new EntitySet<Urun>(new Action<Urun>(this.attach_Uruns), new Action<Urun>(this.detach_Uruns));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markaKod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int markaKod
		{
			get
			{
				return this._markaKod;
			}
			set
			{
				if ((this._markaKod != value))
				{
					this.OnmarkaKodChanging(value);
					this.SendPropertyChanging();
					this._markaKod = value;
					this.SendPropertyChanged("markaKod");
					this.OnmarkaKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Marka", DbType="VarChar(50)")]
		public string Marka
		{
			get
			{
				return this._Marka;
			}
			set
			{
				if ((this._Marka != value))
				{
					this.OnMarkaChanging(value);
					this.SendPropertyChanging();
					this._Marka = value;
					this.SendPropertyChanged("Marka");
					this.OnMarkaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaTel", DbType="VarChar(15)")]
		public string MarkaTel
		{
			get
			{
				return this._MarkaTel;
			}
			set
			{
				if ((this._MarkaTel != value))
				{
					this.OnMarkaTelChanging(value);
					this.SendPropertyChanging();
					this._MarkaTel = value;
					this.SendPropertyChanged("MarkaTel");
					this.OnMarkaTelChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MarkaResim", DbType="NVarChar(50)")]
		public string MarkaResim
		{
			get
			{
				return this._MarkaResim;
			}
			set
			{
				if ((this._MarkaResim != value))
				{
					this.OnMarkaResimChanging(value);
					this.SendPropertyChanging();
					this._MarkaResim = value;
					this.SendPropertyChanged("MarkaResim");
					this.OnMarkaResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMarka_Urun", Storage="_Uruns", ThisKey="markaKod", OtherKey="markaKod")]
		public EntitySet<Urun> Uruns
		{
			get
			{
				return this._Uruns;
			}
			set
			{
				this._Uruns.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.tblMarka = this;
		}
		
		private void detach_Uruns(Urun entity)
		{
			this.SendPropertyChanging();
			entity.tblMarka = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSepet")]
	public partial class tblSepet : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _kullaniciKod;
		
		private int _Id;
		
		private int _urunKod;
		
		private System.Nullable<int> _adet;
		
		private EntityRef<tblKullanici> _tblKullanici;
		
		private EntityRef<Urun> _Urun;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnkullaniciKodChanging(int value);
    partial void OnkullaniciKodChanged();
    partial void OnIdChanging(int value);
    partial void OnIdChanged();
    partial void OnurunKodChanging(int value);
    partial void OnurunKodChanged();
    partial void OnadetChanging(System.Nullable<int> value);
    partial void OnadetChanged();
    #endregion
		
		public tblSepet()
		{
			this._tblKullanici = default(EntityRef<tblKullanici>);
			this._Urun = default(EntityRef<Urun>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciKod", DbType="Int NOT NULL")]
		public int kullaniciKod
		{
			get
			{
				return this._kullaniciKod;
			}
			set
			{
				if ((this._kullaniciKod != value))
				{
					if (this._tblKullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkullaniciKodChanging(value);
					this.SendPropertyChanging();
					this._kullaniciKod = value;
					this.SendPropertyChanged("kullaniciKod");
					this.OnkullaniciKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Id
		{
			get
			{
				return this._Id;
			}
			set
			{
				if ((this._Id != value))
				{
					this.OnIdChanging(value);
					this.SendPropertyChanging();
					this._Id = value;
					this.SendPropertyChanged("Id");
					this.OnIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunKod", DbType="Int NOT NULL")]
		public int urunKod
		{
			get
			{
				return this._urunKod;
			}
			set
			{
				if ((this._urunKod != value))
				{
					if (this._Urun.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnurunKodChanging(value);
					this.SendPropertyChanging();
					this._urunKod = value;
					this.SendPropertyChanged("urunKod");
					this.OnurunKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="Int")]
		public System.Nullable<int> adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKullanici_tblSepet", Storage="_tblKullanici", ThisKey="kullaniciKod", OtherKey="kullaniciKod", IsForeignKey=true, DeleteOnNull=true, DeleteRule="CASCADE")]
		public tblKullanici tblKullanici
		{
			get
			{
				return this._tblKullanici.Entity;
			}
			set
			{
				tblKullanici previousValue = this._tblKullanici.Entity;
				if (((previousValue != value) 
							|| (this._tblKullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKullanici.Entity = null;
						previousValue.tblSepets.Remove(this);
					}
					this._tblKullanici.Entity = value;
					if ((value != null))
					{
						value.tblSepets.Add(this);
						this._kullaniciKod = value.kullaniciKod;
					}
					else
					{
						this._kullaniciKod = default(int);
					}
					this.SendPropertyChanged("tblKullanici");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urun_tblSepet", Storage="_Urun", ThisKey="urunKod", OtherKey="urunKod", IsForeignKey=true)]
		public Urun Urun
		{
			get
			{
				return this._Urun.Entity;
			}
			set
			{
				Urun previousValue = this._Urun.Entity;
				if (((previousValue != value) 
							|| (this._Urun.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Urun.Entity = null;
						previousValue.tblSepets.Remove(this);
					}
					this._Urun.Entity = value;
					if ((value != null))
					{
						value.tblSepets.Add(this);
						this._urunKod = value.urunKod;
					}
					else
					{
						this._urunKod = default(int);
					}
					this.SendPropertyChanged("Urun");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSiparis")]
	public partial class tblSipari : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _faturaKod;
		
		private System.Nullable<int> _kullaniciKod;
		
		private System.Nullable<double> _ToplamTutar;
		
		private string _KargoBilgisi;
		
		private System.Nullable<System.DateTime> _siparisTarih;
		
		private System.Nullable<bool> _Onay;
		
		private EntitySet<tblSiparisDetay> _tblSiparisDetays;
		
		private EntityRef<tblKullanici> _tblKullanici;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnfaturaKodChanging(int value);
    partial void OnfaturaKodChanged();
    partial void OnkullaniciKodChanging(System.Nullable<int> value);
    partial void OnkullaniciKodChanged();
    partial void OnToplamTutarChanging(System.Nullable<double> value);
    partial void OnToplamTutarChanged();
    partial void OnKargoBilgisiChanging(string value);
    partial void OnKargoBilgisiChanged();
    partial void OnsiparisTarihChanging(System.Nullable<System.DateTime> value);
    partial void OnsiparisTarihChanged();
    partial void OnOnayChanging(System.Nullable<bool> value);
    partial void OnOnayChanged();
    #endregion
		
		public tblSipari()
		{
			this._tblSiparisDetays = new EntitySet<tblSiparisDetay>(new Action<tblSiparisDetay>(this.attach_tblSiparisDetays), new Action<tblSiparisDetay>(this.detach_tblSiparisDetays));
			this._tblKullanici = default(EntityRef<tblKullanici>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faturaKod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int faturaKod
		{
			get
			{
				return this._faturaKod;
			}
			set
			{
				if ((this._faturaKod != value))
				{
					this.OnfaturaKodChanging(value);
					this.SendPropertyChanging();
					this._faturaKod = value;
					this.SendPropertyChanged("faturaKod");
					this.OnfaturaKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_kullaniciKod", DbType="Int")]
		public System.Nullable<int> kullaniciKod
		{
			get
			{
				return this._kullaniciKod;
			}
			set
			{
				if ((this._kullaniciKod != value))
				{
					if (this._tblKullanici.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnkullaniciKodChanging(value);
					this.SendPropertyChanging();
					this._kullaniciKod = value;
					this.SendPropertyChanged("kullaniciKod");
					this.OnkullaniciKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ToplamTutar", DbType="Float")]
		public System.Nullable<double> ToplamTutar
		{
			get
			{
				return this._ToplamTutar;
			}
			set
			{
				if ((this._ToplamTutar != value))
				{
					this.OnToplamTutarChanging(value);
					this.SendPropertyChanging();
					this._ToplamTutar = value;
					this.SendPropertyChanged("ToplamTutar");
					this.OnToplamTutarChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KargoBilgisi", DbType="VarChar(550)")]
		public string KargoBilgisi
		{
			get
			{
				return this._KargoBilgisi;
			}
			set
			{
				if ((this._KargoBilgisi != value))
				{
					this.OnKargoBilgisiChanging(value);
					this.SendPropertyChanging();
					this._KargoBilgisi = value;
					this.SendPropertyChanged("KargoBilgisi");
					this.OnKargoBilgisiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_siparisTarih", DbType="DateTime")]
		public System.Nullable<System.DateTime> siparisTarih
		{
			get
			{
				return this._siparisTarih;
			}
			set
			{
				if ((this._siparisTarih != value))
				{
					this.OnsiparisTarihChanging(value);
					this.SendPropertyChanging();
					this._siparisTarih = value;
					this.SendPropertyChanged("siparisTarih");
					this.OnsiparisTarihChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Onay", DbType="Bit")]
		public System.Nullable<bool> Onay
		{
			get
			{
				return this._Onay;
			}
			set
			{
				if ((this._Onay != value))
				{
					this.OnOnayChanging(value);
					this.SendPropertyChanging();
					this._Onay = value;
					this.SendPropertyChanged("Onay");
					this.OnOnayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSipari_tblSiparisDetay", Storage="_tblSiparisDetays", ThisKey="faturaKod", OtherKey="faturaKod")]
		public EntitySet<tblSiparisDetay> tblSiparisDetays
		{
			get
			{
				return this._tblSiparisDetays;
			}
			set
			{
				this._tblSiparisDetays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblKullanici_tblSipari", Storage="_tblKullanici", ThisKey="kullaniciKod", OtherKey="kullaniciKod", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblKullanici tblKullanici
		{
			get
			{
				return this._tblKullanici.Entity;
			}
			set
			{
				tblKullanici previousValue = this._tblKullanici.Entity;
				if (((previousValue != value) 
							|| (this._tblKullanici.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblKullanici.Entity = null;
						previousValue.tblSiparis.Remove(this);
					}
					this._tblKullanici.Entity = value;
					if ((value != null))
					{
						value.tblSiparis.Add(this);
						this._kullaniciKod = value.kullaniciKod;
					}
					else
					{
						this._kullaniciKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblKullanici");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSiparisDetays(tblSiparisDetay entity)
		{
			this.SendPropertyChanging();
			entity.tblSipari = this;
		}
		
		private void detach_tblSiparisDetays(tblSiparisDetay entity)
		{
			this.SendPropertyChanging();
			entity.tblSipari = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.tblSiparisDetay")]
	public partial class tblSiparisDetay : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _SatirNo;
		
		private System.Nullable<int> _faturaKod;
		
		private System.Nullable<int> _urunKod;
		
		private System.Nullable<double> _fiyat;
		
		private System.Nullable<double> _KDV;
		
		private System.Nullable<short> _adet;
		
		private EntityRef<tblSipari> _tblSipari;
		
		private EntityRef<Urun> _Urun;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSatirNoChanging(int value);
    partial void OnSatirNoChanged();
    partial void OnfaturaKodChanging(System.Nullable<int> value);
    partial void OnfaturaKodChanged();
    partial void OnurunKodChanging(System.Nullable<int> value);
    partial void OnurunKodChanged();
    partial void OnfiyatChanging(System.Nullable<double> value);
    partial void OnfiyatChanged();
    partial void OnKDVChanging(System.Nullable<double> value);
    partial void OnKDVChanged();
    partial void OnadetChanging(System.Nullable<short> value);
    partial void OnadetChanged();
    #endregion
		
		public tblSiparisDetay()
		{
			this._tblSipari = default(EntityRef<tblSipari>);
			this._Urun = default(EntityRef<Urun>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SatirNo", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int SatirNo
		{
			get
			{
				return this._SatirNo;
			}
			set
			{
				if ((this._SatirNo != value))
				{
					this.OnSatirNoChanging(value);
					this.SendPropertyChanging();
					this._SatirNo = value;
					this.SendPropertyChanged("SatirNo");
					this.OnSatirNoChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_faturaKod", DbType="Int")]
		public System.Nullable<int> faturaKod
		{
			get
			{
				return this._faturaKod;
			}
			set
			{
				if ((this._faturaKod != value))
				{
					if (this._tblSipari.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnfaturaKodChanging(value);
					this.SendPropertyChanging();
					this._faturaKod = value;
					this.SendPropertyChanged("faturaKod");
					this.OnfaturaKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunKod", DbType="Int")]
		public System.Nullable<int> urunKod
		{
			get
			{
				return this._urunKod;
			}
			set
			{
				if ((this._urunKod != value))
				{
					if (this._Urun.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnurunKodChanging(value);
					this.SendPropertyChanging();
					this._urunKod = value;
					this.SendPropertyChanged("urunKod");
					this.OnurunKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_fiyat", DbType="Float")]
		public System.Nullable<double> fiyat
		{
			get
			{
				return this._fiyat;
			}
			set
			{
				if ((this._fiyat != value))
				{
					this.OnfiyatChanging(value);
					this.SendPropertyChanging();
					this._fiyat = value;
					this.SendPropertyChanged("fiyat");
					this.OnfiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KDV", DbType="Float")]
		public System.Nullable<double> KDV
		{
			get
			{
				return this._KDV;
			}
			set
			{
				if ((this._KDV != value))
				{
					this.OnKDVChanging(value);
					this.SendPropertyChanging();
					this._KDV = value;
					this.SendPropertyChanged("KDV");
					this.OnKDVChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_adet", DbType="SmallInt")]
		public System.Nullable<short> adet
		{
			get
			{
				return this._adet;
			}
			set
			{
				if ((this._adet != value))
				{
					this.OnadetChanging(value);
					this.SendPropertyChanging();
					this._adet = value;
					this.SendPropertyChanged("adet");
					this.OnadetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblSipari_tblSiparisDetay", Storage="_tblSipari", ThisKey="faturaKod", OtherKey="faturaKod", IsForeignKey=true, DeleteRule="CASCADE")]
		public tblSipari tblSipari
		{
			get
			{
				return this._tblSipari.Entity;
			}
			set
			{
				tblSipari previousValue = this._tblSipari.Entity;
				if (((previousValue != value) 
							|| (this._tblSipari.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblSipari.Entity = null;
						previousValue.tblSiparisDetays.Remove(this);
					}
					this._tblSipari.Entity = value;
					if ((value != null))
					{
						value.tblSiparisDetays.Add(this);
						this._faturaKod = value.faturaKod;
					}
					else
					{
						this._faturaKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblSipari");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urun_tblSiparisDetay", Storage="_Urun", ThisKey="urunKod", OtherKey="urunKod", IsForeignKey=true, DeleteRule="CASCADE")]
		public Urun Urun
		{
			get
			{
				return this._Urun.Entity;
			}
			set
			{
				Urun previousValue = this._Urun.Entity;
				if (((previousValue != value) 
							|| (this._Urun.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Urun.Entity = null;
						previousValue.tblSiparisDetays.Remove(this);
					}
					this._Urun.Entity = value;
					if ((value != null))
					{
						value.tblSiparisDetays.Add(this);
						this._urunKod = value.urunKod;
					}
					else
					{
						this._urunKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("Urun");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Urun")]
	public partial class Urun : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _urunKod;
		
		private System.Nullable<int> _markaKod;
		
		private string _urunAd;
		
		private System.Nullable<int> _KatId;
		
		private System.Nullable<double> _listeFiyat;
		
		private System.Nullable<double> _Indirim;
		
		private System.Nullable<double> _KDVoran;
		
		private string _urunResim;
		
		private string _urunOzet;
		
		private System.Nullable<int> _stokDurum;
		
		private string _garanti;
		
		private System.Nullable<byte> _teslimatSure;
		
		private System.Nullable<bool> _IndirimliMi;
		
		private string _Detay;
		
		private System.Nullable<bool> _Sil;
		
		private EntitySet<tblSepet> _tblSepets;
		
		private EntitySet<tblSiparisDetay> _tblSiparisDetays;
		
		private EntityRef<tblMarka> _tblMarka;
		
		private EntityRef<Kategori> _Kategori;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnurunKodChanging(int value);
    partial void OnurunKodChanged();
    partial void OnmarkaKodChanging(System.Nullable<int> value);
    partial void OnmarkaKodChanged();
    partial void OnurunAdChanging(string value);
    partial void OnurunAdChanged();
    partial void OnKatIdChanging(System.Nullable<int> value);
    partial void OnKatIdChanged();
    partial void OnlisteFiyatChanging(System.Nullable<double> value);
    partial void OnlisteFiyatChanged();
    partial void OnIndirimChanging(System.Nullable<double> value);
    partial void OnIndirimChanged();
    partial void OnKDVoranChanging(System.Nullable<double> value);
    partial void OnKDVoranChanged();
    partial void OnurunResimChanging(string value);
    partial void OnurunResimChanged();
    partial void OnurunOzetChanging(string value);
    partial void OnurunOzetChanged();
    partial void OnstokDurumChanging(System.Nullable<int> value);
    partial void OnstokDurumChanged();
    partial void OngarantiChanging(string value);
    partial void OngarantiChanged();
    partial void OnteslimatSureChanging(System.Nullable<byte> value);
    partial void OnteslimatSureChanged();
    partial void OnIndirimliMiChanging(System.Nullable<bool> value);
    partial void OnIndirimliMiChanged();
    partial void OnDetayChanging(string value);
    partial void OnDetayChanged();
    partial void OnSilChanging(System.Nullable<bool> value);
    partial void OnSilChanged();
    #endregion
		
		public Urun()
		{
			this._tblSepets = new EntitySet<tblSepet>(new Action<tblSepet>(this.attach_tblSepets), new Action<tblSepet>(this.detach_tblSepets));
			this._tblSiparisDetays = new EntitySet<tblSiparisDetay>(new Action<tblSiparisDetay>(this.attach_tblSiparisDetays), new Action<tblSiparisDetay>(this.detach_tblSiparisDetays));
			this._tblMarka = default(EntityRef<tblMarka>);
			this._Kategori = default(EntityRef<Kategori>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunKod", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int urunKod
		{
			get
			{
				return this._urunKod;
			}
			set
			{
				if ((this._urunKod != value))
				{
					this.OnurunKodChanging(value);
					this.SendPropertyChanging();
					this._urunKod = value;
					this.SendPropertyChanged("urunKod");
					this.OnurunKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_markaKod", DbType="Int")]
		public System.Nullable<int> markaKod
		{
			get
			{
				return this._markaKod;
			}
			set
			{
				if ((this._markaKod != value))
				{
					if (this._tblMarka.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnmarkaKodChanging(value);
					this.SendPropertyChanging();
					this._markaKod = value;
					this.SendPropertyChanged("markaKod");
					this.OnmarkaKodChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunAd", DbType="VarChar(255)")]
		public string urunAd
		{
			get
			{
				return this._urunAd;
			}
			set
			{
				if ((this._urunAd != value))
				{
					this.OnurunAdChanging(value);
					this.SendPropertyChanging();
					this._urunAd = value;
					this.SendPropertyChanged("urunAd");
					this.OnurunAdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KatId", DbType="Int")]
		public System.Nullable<int> KatId
		{
			get
			{
				return this._KatId;
			}
			set
			{
				if ((this._KatId != value))
				{
					if (this._Kategori.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnKatIdChanging(value);
					this.SendPropertyChanging();
					this._KatId = value;
					this.SendPropertyChanged("KatId");
					this.OnKatIdChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_listeFiyat", DbType="Float")]
		public System.Nullable<double> listeFiyat
		{
			get
			{
				return this._listeFiyat;
			}
			set
			{
				if ((this._listeFiyat != value))
				{
					this.OnlisteFiyatChanging(value);
					this.SendPropertyChanging();
					this._listeFiyat = value;
					this.SendPropertyChanged("listeFiyat");
					this.OnlisteFiyatChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indirim", DbType="Float")]
		public System.Nullable<double> Indirim
		{
			get
			{
				return this._Indirim;
			}
			set
			{
				if ((this._Indirim != value))
				{
					this.OnIndirimChanging(value);
					this.SendPropertyChanging();
					this._Indirim = value;
					this.SendPropertyChanged("Indirim");
					this.OnIndirimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KDVoran", DbType="Float")]
		public System.Nullable<double> KDVoran
		{
			get
			{
				return this._KDVoran;
			}
			set
			{
				if ((this._KDVoran != value))
				{
					this.OnKDVoranChanging(value);
					this.SendPropertyChanging();
					this._KDVoran = value;
					this.SendPropertyChanged("KDVoran");
					this.OnKDVoranChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunResim", DbType="VarChar(55)")]
		public string urunResim
		{
			get
			{
				return this._urunResim;
			}
			set
			{
				if ((this._urunResim != value))
				{
					this.OnurunResimChanging(value);
					this.SendPropertyChanging();
					this._urunResim = value;
					this.SendPropertyChanged("urunResim");
					this.OnurunResimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_urunOzet", DbType="VarChar(255)")]
		public string urunOzet
		{
			get
			{
				return this._urunOzet;
			}
			set
			{
				if ((this._urunOzet != value))
				{
					this.OnurunOzetChanging(value);
					this.SendPropertyChanging();
					this._urunOzet = value;
					this.SendPropertyChanged("urunOzet");
					this.OnurunOzetChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_stokDurum", DbType="Int")]
		public System.Nullable<int> stokDurum
		{
			get
			{
				return this._stokDurum;
			}
			set
			{
				if ((this._stokDurum != value))
				{
					this.OnstokDurumChanging(value);
					this.SendPropertyChanging();
					this._stokDurum = value;
					this.SendPropertyChanged("stokDurum");
					this.OnstokDurumChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_garanti", DbType="VarChar(50)")]
		public string garanti
		{
			get
			{
				return this._garanti;
			}
			set
			{
				if ((this._garanti != value))
				{
					this.OngarantiChanging(value);
					this.SendPropertyChanging();
					this._garanti = value;
					this.SendPropertyChanged("garanti");
					this.OngarantiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_teslimatSure", DbType="TinyInt")]
		public System.Nullable<byte> teslimatSure
		{
			get
			{
				return this._teslimatSure;
			}
			set
			{
				if ((this._teslimatSure != value))
				{
					this.OnteslimatSureChanging(value);
					this.SendPropertyChanging();
					this._teslimatSure = value;
					this.SendPropertyChanged("teslimatSure");
					this.OnteslimatSureChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IndirimliMi", DbType="Bit")]
		public System.Nullable<bool> IndirimliMi
		{
			get
			{
				return this._IndirimliMi;
			}
			set
			{
				if ((this._IndirimliMi != value))
				{
					this.OnIndirimliMiChanging(value);
					this.SendPropertyChanging();
					this._IndirimliMi = value;
					this.SendPropertyChanged("IndirimliMi");
					this.OnIndirimliMiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Detay", DbType="VarChar(MAX)")]
		public string Detay
		{
			get
			{
				return this._Detay;
			}
			set
			{
				if ((this._Detay != value))
				{
					this.OnDetayChanging(value);
					this.SendPropertyChanging();
					this._Detay = value;
					this.SendPropertyChanged("Detay");
					this.OnDetayChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sil", DbType="Bit")]
		public System.Nullable<bool> Sil
		{
			get
			{
				return this._Sil;
			}
			set
			{
				if ((this._Sil != value))
				{
					this.OnSilChanging(value);
					this.SendPropertyChanging();
					this._Sil = value;
					this.SendPropertyChanged("Sil");
					this.OnSilChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urun_tblSepet", Storage="_tblSepets", ThisKey="urunKod", OtherKey="urunKod")]
		public EntitySet<tblSepet> tblSepets
		{
			get
			{
				return this._tblSepets;
			}
			set
			{
				this._tblSepets.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Urun_tblSiparisDetay", Storage="_tblSiparisDetays", ThisKey="urunKod", OtherKey="urunKod")]
		public EntitySet<tblSiparisDetay> tblSiparisDetays
		{
			get
			{
				return this._tblSiparisDetays;
			}
			set
			{
				this._tblSiparisDetays.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="tblMarka_Urun", Storage="_tblMarka", ThisKey="markaKod", OtherKey="markaKod", IsForeignKey=true)]
		public tblMarka tblMarka
		{
			get
			{
				return this._tblMarka.Entity;
			}
			set
			{
				tblMarka previousValue = this._tblMarka.Entity;
				if (((previousValue != value) 
							|| (this._tblMarka.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._tblMarka.Entity = null;
						previousValue.Uruns.Remove(this);
					}
					this._tblMarka.Entity = value;
					if ((value != null))
					{
						value.Uruns.Add(this);
						this._markaKod = value.markaKod;
					}
					else
					{
						this._markaKod = default(Nullable<int>);
					}
					this.SendPropertyChanged("tblMarka");
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="Kategori_Urun", Storage="_Kategori", ThisKey="KatId", OtherKey="Id", IsForeignKey=true)]
		public Kategori Kategori
		{
			get
			{
				return this._Kategori.Entity;
			}
			set
			{
				Kategori previousValue = this._Kategori.Entity;
				if (((previousValue != value) 
							|| (this._Kategori.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._Kategori.Entity = null;
						previousValue.Uruns.Remove(this);
					}
					this._Kategori.Entity = value;
					if ((value != null))
					{
						value.Uruns.Add(this);
						this._KatId = value.Id;
					}
					else
					{
						this._KatId = default(Nullable<int>);
					}
					this.SendPropertyChanged("Kategori");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_tblSepets(tblSepet entity)
		{
			this.SendPropertyChanging();
			entity.Urun = this;
		}
		
		private void detach_tblSepets(tblSepet entity)
		{
			this.SendPropertyChanging();
			entity.Urun = null;
		}
		
		private void attach_tblSiparisDetays(tblSiparisDetay entity)
		{
			this.SendPropertyChanging();
			entity.Urun = this;
		}
		
		private void detach_tblSiparisDetays(tblSiparisDetay entity)
		{
			this.SendPropertyChanging();
			entity.Urun = null;
		}
	}
}
#pragma warning restore 1591
